apiVersion: apps/v1
kind: Deployment
metadata:
  name:  flask-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        # TODO: Replace <DockerHub-Username> with your Docker Hub username, and use the appropriate image name and tag
        image: seanhhh/mlip-lab9-backend:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo 'preStop: sending SIGTERM to backend (PID 1)'; kill -TERM 1; sleep 5"]

        volumeMounts:
        - name: model-volume
          mountPath: /shared-volume
          readOnly: true  # Backend only needs read access
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
---
apiVersion: v1
kind: Service
metadata:
  name:  flask-backend-service # TODO: Specify a unique service name if deploying multiple services
spec:
  type: ClusterIP
  selector:
    app: flask-backend
  ports:
    - port: 5001
      targetPort: 5001
